### ISSUE TITLE
Update to Kokkos 3.5?

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/EKAT#170]
**Is your feature request related to a problem? Please describe.**
The EAGLES computation team is using [TChem](https://github.com/sandialabs/TChem) for aerosol and gas chemical kinetics. TChem makes pretty aggressive use of Kokkos, and recent updates use features exposed in Kokkos 3.5.

**Describe the solution you'd like**
We'd like to update EKAT to use Kokkos 3.5. We've tested that Kokkos 3.5 doesn't cause issues with EKAT the way we use it (in a branch of EKAT we're using within our own repository).

**Comment by bartgol** [comment]
We should first check that it doesn't cause issues in SCREAM. If not, we can probably upgrade, yes.

 On a side note, another project I'm on _might_ have been impacted (in a negative way) by the upgrade, with performance deterioration. But that's only due to atomics, and we're still in the process of verifying this, so not an important thing.
