### ISSUE TITLE
Kokkos::Serial execution space init check won't build

### ISSUE THREAD

**Issue by pbosler** [E3SM-Project/EKAT#20]
**Describe the bug**
`ekat_arch.cpp` line 35 `DefaultDevice::execution_space::impl_is_initialized()` doesn't work with Kokkos serial.

**To Reproduce**
1. Configure only Kokkos::Serial
2. Try to build
3. See error

**bug fix**
Remove "impl" (just use `DefaultDevice::execution_space::is_initialized()`.  

PR coming.

**Comment by bartgol** [comment]
This is an issue of deprecated code on/off. You need to have `-DKOKKOS_ENABLE_DEPRECATED_CODE=OFF` in your configure script (or analogue to that if you use a machine file). All our mach files have that.

I guess we could make ekat more fault-tolerant, and use `impl_is_initialized` or `is_initialized` depending on whether kokkos has deprecated code on/off.

@pbosler , please, verify that the issue is the lack of the above kokkos flag in your config. If so, we can close this. I'll open a separate issue regarding support (or lack thereof) of deprecated kokkos code.

**Comment by pbosler** [comment]
You're right, that's the issue.   I believe newer Kokkos releases set deprecated_code = off by default.  If so, this could be part of #19.
